name: CD Pipeline

on:
  workflow_run:
    workflows: ["CD Pipeline"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull victoryghor/botpcd:latest
      - name: Delete Old docker container
        run: sudo docker rm -f botpcd-container || true
      - name: Run Docker Container
        run: docker run -d -p 8080:8080 --name botpcd-container

